DROP TABLE IF EXISTS recipe CASCADE;

CREATE TABLE recipe (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS direction CASCADE;

CREATE TABLE direction (
  id SERIAL PRIMARY KEY NOT NULL,
  recipe_id INTEGER REFERENCES recipe(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS food_type CASCADE;

CREATE TABLE food_type (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS ingredient CASCADE;

CREATE TABLE ingredient (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  type_id INTEGER REFERENCES food_type(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS ingredient_list CASCADE;

CREATE TABLE ingredient_list (
  id SERIAL PRIMARY KEY NOT NULL,
  recipe_id INTEGER REFERENCES recipe(id) ON DELETE CASCADE,
  ingredient_id INTEGER REFERENCES ingredient(id) ON DELETE CASCADE,
  measurement VARCHAR(255)
);

